- name: Exclui instâncias EC2 e VPC
  hosts: localhost
  vars_files:
  - vars/main.yaml

  tasks:
    - name: Excluindo a instância EC2
      amazon.aws.ec2_instance:
        region: '{{ region }}'
        state: absent
        aws_access_key: '{{ aws_access_key }}'
        aws_secret_key: '{{ aws_secret_key }}'
        aws_session_token: '{{ aws_session_token }}'
        filters:
          "tag:Name": '{{ instance_name }}'
      no_log: true

    - name: Excluindo grupo de segurança
      amazon.aws.ec2_security_group:
        region: '{{ region }}'
        state: absent
        aws_access_key: '{{ aws_access_key }}'
        aws_secret_key: '{{ aws_secret_key }}'
        aws_session_token: '{{ aws_session_token }}'
        name: '{{ security_group_name }}'

    - name: Excluindo par de chaves
      amazon.aws.ec2_key:
        region: '{{ region }}'
        state: absent
        name: '{{ key_name }}'
        aws_access_key: '{{ aws_access_key }}'
        aws_secret_key: '{{ aws_secret_key }}'
        aws_session_token: '{{ aws_session_token }}'

    - name: Excluindo par de chaves localmente
      file:
        path: ../../utils/credentials/keypair.pem
        state: absent